import Head from 'next/head';
import DefaultUser from '../lib/defaultUser';
import { MdExpandLess } from 'react-icons/md';

import player from '../lib/player';
import artist from '../lib/artist';
import track from '../lib/track';
import login from '../components/login';
import Player from '../components/Player';
import Login from '../components/login';
import { useState } from 'react';
import Profile from '../components/Profile';
import Sidebar from '../components/Sidebar';
import Main from '../components/Main';
import CreatePlaylistModal from '../components/CreatePlaylistModal';
import CreateTrackModal from '../components/CreateTrackModal';

export default function Home() {
  /* const Artist = new artist();
  Artist.name = 'Jamaika';
  Artist.createTrack(
    'Anklage',
    'https://images.genius.com/6a88939782e3dcf5cc5151dcfc5f0234.1000x1000x1.jpg',
    'file',
    180
  );
  console.log(Artist);

  player.currentTrack = Artist.tracks[0];
  console.log(player); */

  const [user, setUser] = useState();
  const [createPlaylistModal, setCreatePlaylistModal] = useState(false);
  const [createTrackModal, setCreateTrackModal] = useState(false);
  const [queue, setQueue] = useState([]);
  const [currentTrack, setCurrentTrack] = useState(null);

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <meta name='viewport' content='width=device-width, initial-scale=1' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      {!user && <Login user={user} setUser={setUser} />}

      {createPlaylistModal && (
        <CreatePlaylistModal
          user={user}
          createPlaylistModal={createPlaylistModal}
          setCreatePlaylistModal={setCreatePlaylistModal}
        />
      )}

      {createTrackModal && (
        <CreateTrackModal
          user={user}
          createTrackModal={createTrackModal}
          setCreateTrackModal={setCreateTrackModal}
        />
      )}

      <div className='relative'>
        {user && <Profile user={user} />}

        <div className='flex h-screen'>
          <Sidebar
            user={user}
            createPlaylistModal={createPlaylistModal}
            setCreatePlaylistModal={setCreatePlaylistModal}
            createTrackModal={createTrackModal}
            setCreateTrackModal={setCreateTrackModal}
          />

          <Main
            user={user}
            currentTrack={currentTrack}
            setCurrentTrack={setCurrentTrack}
          />
        </div>

        <Player currentTrack={currentTrack} queue={queue} />
      </div>
    </>
  );
}
